/**
 * Initializes and exports a singleton instance of the PrismaClient for database interactions.
 * 
 * - Ensures that only one instance of PrismaClient is created and reused across the application.
 * - In non-production environments, the PrismaClient instance is attached to the `globalThis` object
 *   to prevent multiple instances during hot-reloading in development.
 * 
 * @remarks
 * PrismaClient is a database client generated by Prisma, used to interact with the database.
 * 
 * @see {@link https://www.prisma.io/docs/concepts/components/prisma-client | Prisma Client Documentation}
 * 
 * @example
 * ```typescript
 * import { db } from './lib/db';
 * 
 * const users = await db.user.findMany();
 * console.log(users);
 * ```
 */
import { PrismaClient } from '@prisma/client';

declare global {
	var prisma: PrismaClient | undefined;
}

export const db = globalThis.prisma || new PrismaClient();

if (process.env.NODE_ENV !== 'production') globalThis.prisma = db;
